name: olmat_prod_pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /public_html/dev-olmat
            git reset --hard
            git pull
            yarn install
            yarn start:production
            pm2 reload ecosystem-production.config.js
